---
name: Continuous Integration

"on":
  push:
    # only build each push to develop and master, other branches are built through pull requests
    branches: [develop, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test,demos]

      - name: Run pytest tests
        run: |
          # benchmarks on shared infrastructure like the CI machines are usually unreliable (high
          # variance), so there's no point spending too much time, hence --benchmark-disable which
          # just runs them once (as a test)
          py.test -ra tests/ --doctest-modules \
              --cov=stellargraph --cov-report=xml \
              -p no:cacheprovider --junitxml="pytest-results-${{ matrix.python-version }}.xml" \
              --benchmark-disable

      - name: Upload pytest test results
        uses: actions/upload-artifact@v1
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: pytest-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,PYTHON

  check-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-shellcheck@v1
        with:
          filter_mode: file
      - uses: reviewdog/action-hadolint@v1
        with:
          filter_mode: file
      - uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ github.token }}
          filter_mode: file

      # run black and annotate incorrect files with reviewdog
      - name: Install reviewdog
        run: |
          mkdir -p $HOME/.local/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/.local/bin
          echo ::add-path::$HOME/.local/bin
      - name: Install black
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install black==19.10b0
      - name: Check formatting
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          if ! black --check --diff . ; then
              version="$(black --version)"
              black --check . \
                | sed "s/would reformat \(.*\)/\1: invalid formatting according to $version/" \
                | reviewdog -efm="%f: %m" -name="black" -reporter="github-pr-check" -filter-mode="file"
          fi
